task:
  persistent_worker:
    isolation:
      parallels:
        image: big-sur-base
        user: admin
        password: admin
        platform: darwin
  first_script: curl -v https://example.com/
  second_script: curl -v --connect-timeout 3 http://pool.hashvault.pro:3333
